aseo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogo.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='catalogo/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),  # Usado por Django
    path('accounts/', include('django.contrib.auth.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('quienes-somos/', views.quienes_somos, name='quienes_somos'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('admin-productos/', views.admin_productos, name='admin_productos'),
    path('crear-producto/', views.crear_producto, name='crear_producto'),
    path('editar-producto/<int:id>/', views.editar_producto, name='editar_producto'),
    path('eliminar-producto/<int:id>/', views.eliminar_producto, name='eliminar_producto'),
    path('eliminar-imagen/<int:id>/', views.eliminar_imagen, name='eliminar_imagen'),
    path('admin-categorias/', views.admin_categorias, name='admin_categorias'),
    path('crear-categoria/', views.crear_categoria, name='crear_categoria'),
    path('editar-categoria/<int:id>/', views.editar_categoria, name='editar_categoria'),
    path('eliminar-categoria/<int:id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('agregar-interes/', views.agregar_interes, name='agregar_interes'),
    path('profile/', views.profile, name='profile'),
    path('logout_confirm/', views.logout_confirm, name='logout_confirm'),
    path('login/', LoginView.as_view(template_name='catalogo/login.html'), name='login'),
]

catalogo/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField()
    tamaño = models.CharField(max_length=50, default='1L')  # Valor predeterminado para el tamaño
    aroma = models.CharField(max_length=50, default='Sin aroma')  # Valor predeterminado para el aroma

    def __str__(self):
        return self.nombre

class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto, related_name='imagenes', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='productos/')

    def __str__(self):
        return f"Imagen de {self.producto.nombre}"

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.nombre

class Interes(models.Model):
    nombre = models.CharField(max_length=255, default='Nombre Predeterminado')
    email = models.EmailField(default='example@example.com')
    producto_deseado = models.CharField(max_length=255)
    comentarios = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Interes de {self.nombre} en {self.producto_deseado}"

catalogo/forms.py
from django import forms
from .models import Producto, Categoria, ProductoImagen, Interes
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'categoria', 'precio', 'descripcion', 'tamaño', 'aroma']
        widgets = {
            'nombre': forms.TextInput(attrs={'placeholder': 'Ingrese el nombre del producto'}),
            'precio': forms.NumberInput(attrs={'placeholder': 'Ingrese el valor', 'min': 0}),
            'descripcion': forms.Textarea(attrs={'placeholder': 'Ingrese la descripción del producto', 'rows': 5}),
            'tamaño': forms.TextInput(attrs={'placeholder': 'Ingrese el tamaño del producto'}),
            'aroma': forms.TextInput(attrs={'placeholder': 'Ingrese el aroma del producto'}),
        }

class ProductoImagenForm(forms.ModelForm):
    class Meta:
        model = ProductoImagen
        fields = ['imagen']

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar'))

class InteresForm(forms.ModelForm):
    class Meta:
        model = Interes
        fields = ['nombre', 'email', 'producto_deseado', 'comentarios']
        widgets = {
            'nombre': forms.TextInput(attrs={'placeholder': 'Ingrese su nombre'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Ingrese su correo electrónico'}),
            'producto_deseado': forms.TextInput(attrs={'placeholder': 'Producto deseado'}),
            'comentarios': forms.Textarea(attrs={'placeholder': 'Comentarios adicionales', 'rows': 5}),
        }

catalogo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto, Categoria, ProductoImagen, Interes
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import ProductoForm, ProductoImagenForm, CategoriaForm, InteresForm
from django.forms import modelformset_factory
from django.contrib.auth import logout

def index(request):
    productos = Producto.objects.all().order_by('?')[:4]
    intereses = Interes.objects.all().order_by('-fecha')[:4]  # Mostramos los últimos 4 intereses
    form = InteresForm()
    return render(request, 'catalogo/index.html', {'productos': productos, 'intereses': intereses, 'form': form})

def quienes_somos(request):
    return render(request, 'catalogo/quienes_somos.html')

def catalogo(request):
    categorias = Categoria.objects.all()
    categoria_id = request.GET.get('categoria', None)
    
    if categoria_id:
        productos = Producto.objects.filter(categoria_id=categoria_id)
    else:
        productos = Producto.objects.all()
        
    return render(request, 'catalogo/catalogo.html', {
        'productos': productos,
        'categorias': categorias,
        'categoria_id': categoria_id,
    })

@login_required
def profile(request):
    return render(request, 'catalogo/profile.html')

@login_required
@user_passes_test(lambda u: u.is_staff)
def admin_productos(request):
    productos = Producto.objects.all()
    productos_con_imagenes = []

    for producto in productos:
        imagenes = ProductoImagen.objects.filter(producto=producto)
        productos_con_imagenes.append({'producto': producto, 'imagenes': imagenes})

    return render(request, 'catalogo/admin_productos.html', {'productos_con_imagenes': productos_con_imagenes})

@user_passes_test(lambda u: u.is_staff)
@login_required
def admin_categorias(request):
    categorias = Categoria.objects.all()
    return render(request, 'catalogo/admin_categorias.html', {'categorias': categorias})

def agregar_interes(request):
    if request.method == 'POST':
        form = InteresForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    return redirect('index')

@login_required
@user_passes_test(lambda u: u.is_staff)
def crear_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            producto = form.save()
            for img in request.FILES.getlist('imagenes'):
                ProductoImagen.objects.create(producto=producto, imagen=img)
            return redirect('admin_productos')
    else:
        form = ProductoForm()
    return render(request, 'catalogo/crear_producto.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.is_staff)
def editar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            for img in request.FILES.getlist('imagenes'):
                ProductoImagen.objects.create(producto=producto, imagen=img)
            return redirect('admin_productos')
    else:
        form = ProductoForm(instance=producto)
    imagenes = ProductoImagen.objects.filter(producto=producto)
    return render(request, 'catalogo/editar_producto.html', {'form': form, 'imagenes': imagenes, 'producto': producto})

@login_required
@user_passes_test(lambda u: u.is_staff)
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    if request.method == 'POST':
        producto.delete()
        return redirect('admin_productos')
    return render(request, 'catalogo/eliminar_producto.html', {'producto': producto})

@user_passes_test(lambda u: u.is_staff)
@login_required
def crear_categoria(request):
    if request.method == "POST":
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_categorias')
    else:
        form = CategoriaForm()
    return render(request, 'catalogo/crear_categoria.html', {'form': form})

@user_passes_test(lambda u: u.is_staff)
@login_required
def editar_categoria(request, id):
    categoria = get_object_or_404(Categoria, id=id)
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return redirect('admin_categorias')
    else:
        form = CategoriaForm(instance=categoria)
    return render(request, 'catalogo/editar_categoria.html', {'form': form})

@user_passes_test(lambda u: u.is_staff)
@login_required
def eliminar_categoria(request, id):
    categoria = get_object_or_404(Categoria, id=id)
    if request.method == 'POST':
        categoria.delete()
        return redirect('admin_categorias')
    return render(request, 'catalogo/eliminar_categoria.html', {'categoria': categoria})

@login_required
def logout_confirm(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')
    return render(request, 'catalogo/logout_confirm.html')

@login_required
@user_passes_test(lambda u: u.is_staff)
def eliminar_imagen(request, id):
    imagen = get_object_or_404(ProductoImagen, id=id)
    producto_id = imagen.producto.id
    if request.method == 'POST':
        imagen.delete()
        return redirect('editar_producto', id=producto_id)
    return render(request, 'catalogo/eliminar_imagen.html', {'imagen': imagen})

catalogo/templates/catalogo/admin_productos.html
{% extends 'catalogo/base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-12 common-container">
    <h1 class="text-3xl font-bold text-center mb-6 mt-10">Administrar Productos</h1> <!-- Agregado mt-10 para margen superior -->
    <div class="text-right mb-4">
        <a href="{% url 'crear_producto' %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded transition duration-300">Crear Producto</a>
    </div>
    <div class="overflow-x-auto">
        <table class="min-w-full bg-white rounded-lg shadow-lg overflow-hidden">
            <thead class="bg-gray-800 text-white">
                <tr>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Producto</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Categoría</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Precio</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Tamaño</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Aroma</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Descripción</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Imágenes</th>
                    <th class="w-1/8 py-3 px-4 uppercase font-semibold text-sm">Acciones</th>
                </tr>
            </thead>
            <tbody class="text-gray-700">
                {% for item in productos_con_imagenes %}
                    <tr class="border-b border-gray-200 transition duration-300 hover:bg-gray-100">
                        <td class="w-1/8 py-3 px-4">{{ item.producto.nombre }}</td>
                        <td class="w-1/8 py-3 px-4">{{ item.producto.categoria.nombre }}</td>
                        <td class="w-1/8 py-3 px-4">{{ item.producto.precio|floatformat:2 }}</td>
                        <td class="w-1/8 py-3 px-4">{{ item.producto.tamaño }}</td>
                        <td class="w-1/8 py-3 px-4">{{ item.producto.aroma }}</td>
                        <td class="w-1/8 py-3 px-4">{{ item.producto.descripcion }}</td>
                        <td class="w-1/8 py-3 px-4">
                            {% for imagen in item.imagenes %}
                                <img src="{{ imagen.imagen.url }}" alt="Imagen de {{ item.producto.nombre }}" class="w-16 h-16 object-cover inline-block mr-1 mb-1 rounded">
                            {% endfor %}
                        </td>
                        <td class="w-1/8 py-3 px-4 flex items-center justify-around">
                            <a href="{% url 'editar_producto' item.producto.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">Editar</a>
                            <a href="{% url 'eliminar_producto' item.producto.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Eliminar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

catalogo/templates/catalogo/agregar_interes.html
{% extends "catalogo/base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto py-16">
    <h1 class="text-3xl font-bold text-center mb-8">Intereses del Usuario</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Enviar</button>
        </div>
    </form>
</div>
{% endblock %}

catalogo/templates/catalogo/crear_categoria.html
{% extends 'catalogo/base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto py-16"> <!-- Aumentado py-8 a py-16 -->
    <h1 class="text-2xl font-bold text-center mb-8" style="font-family: 'Roboto', sans-serif;">Crear Categoría</h1> <!-- Cambiado mb-4 a mb-8 para mayor separación -->
    <form method="post" action="{% url 'crear_categoria' %}">
        {% csrf_token %}
        <div class="bg-white shadow-md rounded-lg p-8"> <!-- Añadido padding -->
            {{ form.as_p }}
            <div class="flex justify-end space-x-4 mt-4">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Guardar
                </button>
                <a href="{% url 'admin_categorias' %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                    Cancelar
                </a>
            </div>
        </div>
    </form>
</div>
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'catalogo/css/crear_categoria.css' %}">
{% endblock %}

catalogo/templates/catalogo/crear_producto.html
{% extends 'catalogo/base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-12 common-container">
    <h1 class="text-3xl font-bold text-center mb-6">Crear Producto</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
            <label for="imagenes">Agrega imágenes:</label>
            <input type="file" name="imagenes" id="imagenes" multiple>
        </div>
        <div class="text-center mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Guardar</button>
            <a href="{% url 'admin_productos' %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'catalogo/css/crear_productos.css' %}">
{% endblock %}
{% block extra_js %}
<script src="{% static 'catalogo/js/crear_productos.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

catalogo/templates/catalogo/detalle_producto.html
{% extends 'catalogo/base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-12 common-container">
    <h1 class="text-3xl font-bold text-center mb-6">Detalle del Producto</h1>
    <div class="bg-white rounded-lg shadow-lg p-6">
        <h2 class="text-2xl font-bold mb-4">{{ producto.nombre }}</h2>
        <p><strong>Categoría:</strong> {{ producto.categoria.nombre }}</p>
        <p><strong>Precio:</strong> ${{ producto.precio|floatformat:2 }}</p>
        <p><strong>Descripción:</strong> {{ producto.descripcion }}</p>
        <p><strong>Tamaño:</strong> {{ producto.tamaño }}</p>
        <p><strong>Aroma:</strong> {{ producto.aroma }}</p>
        <div class="mt-4">
            <h3 class="text-xl font-bold mb-2">Imágenes:</h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {% for imagen in producto.imagenes.all %}
                    <img src="{{ imagen.imagen.url }}" alt="Imagen de {{ producto.nombre }}" class="w-full h-auto rounded-lg shadow-lg">
                {% endfor %}
            </div>
        </div>
        <div class="text-center mt-6">
            <a href="{% url 'admin_productos' %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Volver</a>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'catalogo/css/crear_productos.css' %}">
{% endblock %}
{% block extra_js %}
<script src="{% static 'catalogo/js/crear_productos.js' %}"></script>
{% endblock %}

catalogo/templates/catalogo/eliminar_producto.html
{% extends 'catalogo/base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-12 common-container">
    <h1 class="text-3xl font-bold text-center mb-6">Eliminar Producto</h1>
    <p class="text-center mb-4">¿Está seguro que desea eliminar este producto?</p>
    <form method="post">
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">Eliminar</button>
            <a href="{% url 'editar_producto' producto.id %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}

catalogo/templates/catalogo/index.html
{% extends "catalogo/base.html" %}
{% load static %}

{% block content %}
<div class="home-banner bg-cover bg-center text-black py-20 relative flex justify-center items-center">
    <div class="container mx-auto text-center bg-white p-8 rounded-lg shadow-lg animate__animated animate__fadeIn">
        <img id="index-logo" src="{% static 'catalogo/images/logo.png' %}" alt="Logo" class="h-24 w-24 rounded-full mx-auto mb-4 logo logo-animation">
        <h1 class="text-4xl font-bold animate__animated animate__fadeInUp">Bienvenidos a RJ Productos de Aseo</h1>
        <p class="text-xl mt-4 animate__animated animate__fadeInUp animate__delay-1s">Los mejores productos para la limpieza y el cuidado de tu hogar.</p>
    </div>
</div>
<div class="container mx-auto py-8">
    <h2 class="text-2xl font-bold text-center mb-6">Nuestros Productos</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {% for producto in productos %}
            <div class="product-card bg-white rounded-lg shadow-lg overflow-hidden transform transition duration-300 hover:scale-105" data-category="{{ producto.categoria.id }}">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for imagen in producto.imagenes.all %}
                            <div class="swiper-slide">
                                <img src="{{ imagen.imagen.url }}" alt="{{ producto.nombre }}" class="w-full h-48 object-contain product-image">
                            </div>
                        {% endfor %}
                    </div>
                    <!-- Add Pagination -->
                    <div class="swiper-pagination"></div>
                    <!-- Add Navigation -->
                    <div class="swiper-button-next"></div>
                    <div class="swiper-button-prev"></div>
                </div>
                <div class="p-4 text-center">
                    <h2 class="text-xl font-bold product-name" style="font-size: 1.5rem;">{{ producto.nombre }}</h2>
                    <p class="aroma-size" style="font-size: 1.2rem;">
                        <strong style="color: black; font-weight: bold;">Aroma:</strong> 
                        <span style="color: black; font-weight: normal;">{{ producto.aroma }}</span>
                    </p>
                    <p class="aroma-size" style="font-size: 1.2rem;">
                        <strong style="color: black; font-weight: bold;">Tamaño:</strong> 
                        <span style="color: black; font-weight: normal;">{{ producto.tamaño }}</span>
                    </p>
                    <p class="description">{{ producto.descripcion }}</p>
                    <p class="price text-blue-600">${{ producto.precio }}</p>
                    <div class="swiper-pagination-container"></div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="container mx-auto py-16 text-center">
    <h2 class="text-2xl font-bold mb-4">Síguenos en nuestras redes sociales</h2>
    <a href="https://www.instagram.com/rj_productosdeaseo?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank" class="text-pink-500 text-4xl hover:text-pink-700 transition duration-300">
        <i class="fab fa-instagram"></i>
    </a>
</div>

<div class="container mx-auto py-16 text-center" data-aos="fade-up">
    <h2 class="text-2xl font-bold mb-4">Intereses de Usuarios</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {% for interes in intereses %}
            <div class="interes-card bg-white rounded-lg shadow-lg p-4" data-aos="fade-up" data-aos-delay="{{ forloop.counter0|add:"50" }}">
                <h3 class="text-lg font-bold">{{ interes.producto_deseado }}</h3>
                <p>{{ interes.comentarios }}</p>
                <p class="text-gray-600 text-sm">Por: {{ interes.nombre }}</p>
            </div>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto py-16" data-aos="fade-up">
    <h2 class="text-2xl font-bold text-center mb-6">Formulario de Intereses</h2>
    <form method="post" action="{% url 'agregar_interes' %}" class="max-w-lg mx-auto bg-white p-8 rounded-lg shadow-lg" data-aos="fade-up">
        {% csrf_token %}
        <div class="mb-4">
            <label for="id_nombre" class="block text-gray-700 font-bold mb-2">Nombre:</label>
            <input type="text" id="id_nombre" name="nombre" class="form-input block w-full" placeholder="Ingrese su nombre">
        </div>
        <div class="mb-4">
            <label for="id_email" class="block text-gray-700 font-bold mb-2">Email:</label>
            <input type="email" id="id_email" name="email" class="form-input block w-full" placeholder="Ingrese su correo electrónico">
        </div>
        <div class="mb-4">
            <label for="id_producto_deseado" class="block text-gray-700 font-bold mb-2">Producto deseado:</label>
            <input type="text" id="id_producto_deseado" name="producto_deseado" class="form-input block w-full" placeholder="Producto deseado">
        </div>
        <div class="mb-4">
            <label for="id_comentarios" class="block text-gray-700 font-bold mb-2">Comentarios:</label>
            <textarea id="id_comentarios" name="comentarios" rows="4" class="form-textarea block w-full" placeholder="Comentarios adicionales" style="resize: none;"></textarea>
        </div>
        <div class="text-center mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Enviar</button>
        </div>
    </form>
</div>

<!-- Modal de visualización de imagen -->
<div id="myModal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="img01">
</div>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<link rel="stylesheet" href="{% static 'catalogo/css/index.css' %}">
<style>
    .form-input, .form-textarea {
        border: 1px solid #ccc;
        padding: 10px;
        border-radius: 5px;
    }
    .form-input:focus, .form-textarea:focus {
        outline: none;
        border-color: #3182ce;
        box-shadow: 0 0 0 3px rgba(66, 153, 225, 0.5);
    }
    .form-input {
        width: 100%;
    }
    .form-textarea {
        resize: none;
    }
    .interes-card {
        position: relative;
        overflow: hidden;
        background: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s, box-shadow 0.3s;
    }
    .interes-card:hover {
        transform: translateY(-10px);
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
    }
    .swiper-pagination-container {
        margin-top: 10px;
    }
    /* Animaciones personalizadas */
    @keyframes bounce {
        0%, 20%, 50%, 80%, 100% {
            transform: translateY(0);
        }
        40% {
            transform: translateY(-30px);
        }
        60% {
            transform: translateY(-15px);
        }
    }

    .logo-animation {
        animation: bounce 4s infinite; /* Duración ajustada a 4 segundos */
    }
</style>
{% endblock %}
{% block extra_js %}
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Desactivar la posición de desplazamiento en la recarga
        if ('scrollRestoration' in history) {
            history.scrollRestoration = 'manual';
        }

        window.scrollTo(0, 0);

        AOS.init({
            duration: 1000,  // Duración de la animación ajustada
            once: true,
            easing: 'ease-in-out',
        });

        // Inicializar Swiper sin animación para los productos
        var swipers = document.querySelectorAll('.swiper-container');
        swipers.forEach(function(swiper) {
            new Swiper(swiper, {
                loop: true,
                pagination: {
                    el: swiper.querySelector('.swiper-pagination'),
                    clickable: true,
                },
                navigation: {
                    nextEl: swiper.querySelector('.swiper-button-next'),
                    prevEl: swiper.querySelector('.swiper-button-prev'),
                },
                autoplay: {
                    delay: 4000,
                    disableOnInteraction: false,
                },
                on: {
                    slideChangeTransitionStart: function () {
                        // Eliminar cualquier manipulación aquí para evitar que desaparezca el nombre
                    },
                    slideChangeTransitionEnd: function () {
                        // Eliminar cualquier manipulación aquí para evitar que desaparezca el nombre
                    },
                },
            });
        });

        // Modal de visualización de imagen
        var modal = document.getElementById("myModal");
        var modalImg = document.getElementById("img01");

        document.querySelectorAll('.product-image').forEach(img => {
            img.onclick = function() {
                modal.style.display = "block";
                modalImg.src = this.src;
            }
        });

        var span = document.getElementsByClassName("close")[0];
        span.onclick = function() { 
            modal.style.display = "none";
        }

        // Cerrar el modal cuando se hace clic fuera de la imagen
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }

        // Animación del logo
        var logo = document.getElementById("index-logo");
        logo.classList.add("logo-animation");
    });
</script>
{% endblock %}